name: Run Node.js Script

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Replace with the desired Node.js version

    # Step 3: Install dependencies (optional)
    - name: Install dependencies
      run: npm install

    # Step 4: Run the Node.js script
    - name: Run Node.js file
      run: forever node index.js  # Replace `your-script.js` with your file name
